"""Writes the manuscript's result tables as LaTeX from the canon and the result files.

Every table that carries a measured number is generated here and pulled into main.tex
with \\input, so a rerun of the protocol regenerates the tables the way it regenerates the
figures, and a number in a table can never disagree with the canon. The captions live
here too, because several of them quote numbers. Both feature extractors of
`satinsight.manuscript.BACKBONES` are reported side by side; a cell whose artifact does
not exist yet is written as a dash, so the tables can be built while a run is in flight.

Usage: tables.py [destination directory]
"""

import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np  # noqa: E402
import pandas as pd  # noqa: E402

from satinsight.manuscript import BACKBONES, CV_NAMES, canon, suffixed  # noqa: E402

OUT = Path(sys.argv[1] if len(sys.argv) > 1 else "docs/manuscript/tables")
DASH = "--"


def thousands(n) -> str:
    return f"{int(n):,}".replace(",", "{,}")


def fmt(value, digits: int = 3) -> str:
    return (
        DASH
        if value is None or (isinstance(value, float) and np.isnan(value))
        else f"{value:.{digits}f}"
    )


def ci(value, low, high, digits: int = 3) -> str:
    if value is None:
        return DASH
    return f"{value:.{digits}f} [{low:.{digits}f}, {high:.{digits}f}]"


def signed(value, low, high, digits: int = 3) -> str:
    return f"${value:+.{digits}f}$ [${low:+.{digits}f}$, ${high:+.{digits}f}$]"


def read(path: str) -> pd.DataFrame | None:
    return pd.read_csv(path) if Path(path).exists() else None


def table(
    name: str,
    caption: str,
    spec: str,
    header: str,
    rows: list[str],
    *,
    label: str,
    small: bool = True,
    resize: bool = False,
) -> None:
    body = "\n".join(rows)
    tabular = f"\\begin{{tabular}}{{{spec}}}\n\\toprule\n{header}\\\\\n\\midrule\n{body}\n\\bottomrule\n\\end{{tabular}}"
    if resize:
        tabular = f"\\resizebox{{\\linewidth}}{{!}}{{%\n{tabular}}}"
    text = (
        "% generated by scripts/tables.py; edit the script, not this file\n"
        "\\begin{table}[htbp]\n\\centering\n"
        f"\\caption{{{caption}}}\n"
        + ("\\small\n" if small else "")
        + tabular
        + f"\n\\label{{{label}}}\n\\end{{table}}\n"
    )
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"{name}.tex").write_text(text)


def blocks(book: dict) -> dict:
    return {tag: (book.get(tag) if tag else book) for tag, _ in BACKBONES}


def curve(book: dict) -> None:
    curve_table(
        book,
        BACKBONES,
        "curve",
        "The supervision-efficiency curve (Fig.~\\ref{fig:curve}a) for both feature extractors. "
        "Within-municipality Spearman $\\rho$ against held-out tract grades, mean over three seeds "
        "(s.d. over seeds on validation); validation cities were used for model selection, test "
        "cities are held out. The 771 row gives the test value of the retrained models and, after "
        "the semicolon, of the validation-selected saved weights that every downstream analysis "
        "scores; the last row gives those saved weights' values with a 95\\% percentile bootstrap "
        "that resamples cities (34 validation and 29 test municipalities).",
        "tab:curve",
        bootstrap=True,
    )


def supp_curve(book: dict) -> None:
    curve_table(
        book,
        (("", "DOFA-B"), ("dofal", "DOFA-L")),
        "supp_curve",
        "The supervision-efficiency curve of the main text repeated on the non-overlapping "
        "extraction of both feature extractors. Within-municipality Spearman $\\rho$ against "
        "held-out tract grades, mean over three seeds (s.d. over seeds on validation); validation "
        "cities were used for model selection, test cities are held out. The 771 row gives the "
        "test value of the retrained models and, after the semicolon, of the validation-selected "
        "saved weights. The rise with the supply of aggregates that DOFA-B shows here on "
        "validation is absent from the sliding-window extraction.",
        "tab:supp_curve",
        bootstrap=False,
    )


def curve_table(
    book: dict, pairs: tuple, name: str, caption: str, label: str, *, bootstrap: bool
) -> None:
    own = {tag: (book.get(tag) if tag else book) for tag, _ in pairs}
    sd = {}
    for tag, _ in pairs:
        path = f"data/supervision_curve_s2_{tag}.csv" if tag else "data/supervision_curve.csv"
        frame = read(path)
        sd[tag] = frame.groupby("bags").spearman_within.std().to_dict() if frame is not None else {}
    intervals = read("data/headline_intervals.csv")
    rows = []
    for bags in (50, 100, 200, 400, 771):
        cells = []
        for tag, _name in pairs:
            b = own[tag]
            if not b:
                cells += [DASH, DASH]
                continue
            v = b["curve"][str(bags)]["spearman_within"]
            t = b["test"]["curve"][str(bags)]
            val = f"{v:.3f} ({sd[tag].get(bags, float('nan')):.3f})"
            test = (
                f"{t:.3f}; {b['test']['headline_token_within']:.3f}" if bags == 771 else f"{t:.3f}"
            )
            cells += [val, test]
        rows.append(f"{bags} & " + " & ".join(cells) + "\\\\")
    boot = []
    for _tag, extractor in pairs:
        if intervals is None:
            boot += [DASH, DASH]
            continue
        sub = intervals[
            (intervals.backbone == extractor)
            & (intervals.estimator == "seed mean")
            & (intervals.unit == "token")
        ]
        for split in ("val", "test"):
            r = sub[sub["split"] == split]
            boot.append(
                ci(float(r.within.iloc[0]), float(r.ci_low.iloc[0]), float(r.ci_high.iloc[0]), 2)
                if len(r)
                else DASH
            )
    if bootstrap:
        rows.append("\\midrule")
        rows.append("771, saved weights [95\\% CI] & " + " & ".join(boot) + "\\\\")
    header = (
        " & ".join(
            [
                "",
                f"\\multicolumn{{2}}{{c}}{{{pairs[0][1]}}}",
                f"\\multicolumn{{2}}{{c}}{{{pairs[1][1]}}}",
            ]
        )
        + "\\\\\n\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\nBags & Validation (s.d.) & Test & Validation (s.d.) & Test"
    )
    table(name, caption, "lcccc", header, rows, label=label)


def backbone_cv(book: dict) -> None:
    cv = book["backbone_cv"]
    reference = CV_NAMES[BACKBONES[0][0]]
    listed = [
        (CV_NAMES[BACKBONES[0][0]], BACKBONES[0][1]),
        (CV_NAMES[BACKBONES[1][0]], BACKBONES[1][1]),
    ]
    rows = cv_rows(cv, listed, reference)
    table(
        "backbone_cv",
        "Feature-extractor comparison under grouped five-fold cross-validation over the 138 "
        "cities of the partition (363 municipalities; 346 with at least five AGEB for the per-AGEB "
        "unit). Within-municipality Spearman $\\rho$ of the seed-mean token score against tract "
        "grades, mean over municipalities, per token and per AGEB, and AUROC for high deprivation "
        "over all tokens. Brackets: 95\\% percentile bootstrap resampling cities. The difference is "
        f"paired against {BACKBONES[0][1]} on the same city draws. Copernicus-FM and the "
        "non-overlapping extraction of both DOFA models are compared in Supplementary "
        "Table~S1.",
        "lccc",
        "Features & Within-$\\rho$, token & Within-$\\rho$, AGEB & AUROC high",
        rows,
        label="tab:backbone",
    )


def cv_rows(cv: dict, listed: list, reference: str) -> list[str]:
    rows = []
    for key, name in listed:
        b = cv["backbones"].get(key)
        if b is None:
            rows.append(f"{name} & {DASH} & {DASH} & {DASH}\\\\")
            continue
        rows.append(
            f"{name} & {ci(b['within_token'], b['within_token_low'], b['within_token_high'])} & "
            f"{ci(b['within_ageb'], b['within_ageb_low'], b['within_ageb_high'])} & {b['auroc_high']:.3f}\\\\"
        )
    rows.append("\\midrule")
    short = dict(listed)
    for d in cv["differences"]:
        if not d["comparison"].endswith(f"minus {reference}"):
            continue
        key = d["comparison"].split(" minus ")[0]
        if key not in short:
            continue
        if d["unit"] == "token":
            rows.append(
                f"{short[key]} minus {BACKBONES[0][1]} & {signed(d['difference'], d['ci_low'], d['ci_high'])} & "
            )
        else:
            rows[-1] += f"{signed(d['difference'], d['ci_low'], d['ci_high'])} & \\\\"
    return rows


def supp_backbone_cv(book: dict) -> None:
    cv = book["backbone_cv"]
    reference = CV_NAMES[BACKBONES[0][0]]
    listed = [
        (CV_NAMES[BACKBONES[0][0]], BACKBONES[0][1]),
        (CV_NAMES[BACKBONES[1][0]], BACKBONES[1][1]),
        ("DOFA base", f"{BACKBONES[0][1]}, non-overlapping windows"),
        ("DOFA large", f"{BACKBONES[1][1]}, non-overlapping windows"),
        ("Copernicus-FM base", "Copernicus-FM, non-overlapping windows"),
    ]
    table(
        "supp_backbone_cv",
        "Every feature extraction under grouped five-fold cross-validation over the 138 "
        "cities of the partition (363 municipalities; 346 with at least five AGEB for the per-AGEB "
        "unit), the protocol of the feature-extractor comparison of the main text. Within-municipality Spearman $\\rho$ "
        "of the seed-mean token score against tract grades, mean over municipalities, per token "
        "and per AGEB, and AUROC for high deprivation over all tokens. Brackets: 95\\% "
        f"percentile bootstrap resampling cities; differences are paired against {BACKBONES[0][1]} "
        "on the same city draws. The non-overlapping rows are the same weights extracted with "
        "224 px windows and no overlap, the extraction whose window-border discontinuities the "
        "sliding window of the main text removes; Copernicus-FM was extracted the same way.",
        "lccc",
        "Features & Within-$\\rho$, token & Within-$\\rho$, AGEB & AUROC high",
        cv_rows(cv, listed, reference),
        label="tab:supp_cv",
        resize=True,
    )


def features(book: dict) -> None:
    own = blocks(book)
    cv = book["backbone_cv"]["backbones"]
    rows = []
    for tag, name in BACKBONES:
        b = own[tag]
        dims = {"ov": (1536, 768), "dofalov": (2048, 1024), "": (1536, 768), "dofal": (2048, 1024)}[
            tag
        ]
        c = cv.get(CV_NAMES[tag])
        cvcell = ci(c["within_token"], c["within_token_low"], c["within_token_high"]) if c else DASH
        if not b:
            rows.append(
                f"{name}, optical and radar fused & {dims[0]} & {DASH} & {DASH} & {cvcell}\\\\"
            )
            continue
        rows.append(
            f"{name}, optical and radar fused & {dims[0]} & {b['curve']['771']['spearman_within']:.3f} & {b['test']['headline_token_within']:.3f} & {cvcell}\\\\"
        )
        for arm, label in (
            ("optical", "optical 10 m"),
            ("degraded", "optical degraded to 20 m"),
            ("radar", "radar"),
        ):
            m = b.get(f"modality_{arm}", {})
            rows.append(
                f"{name}, {label} & {dims[1]} & {fmt(m.get('within'))} & {fmt(b['test']['modality'].get(arm))} & \\\\"
            )
    wc = own[BACKBONES[0][0]] or {}
    rows.append(
        f"WorldCover fractions and NDVI, no encoder & 13 & {fmt(book['modality_worldcover']['within'])} & {fmt(wc.get('test', {}).get('modality', {}).get('worldcover'))} & \\\\"
    )
    table(
        "features",
        "Feature families under one head and one metric: within-municipality Spearman $\\rho$ of "
        "token scores against held-out tract grades, mean over three seeds, on the validation cities "
        "(selection), the held-out test cities (validation-selected models), and under grouped "
        "five-fold cross-validation over all 138 cities with a 95\\% city bootstrap where it was "
        "run. Dimensions are per token. Copernicus-FM, the global grids offered as inputs and the "
        "partially fine-tuned extractor, all run on the non-overlapping extraction, are in "
        "Supplementary Tables~S1 to S3.",
        "llccc",
        "Feature family & Dimensions & Validation & Test & Cross-validation [95\\%]",
        rows,
        label="tab:features",
        resize=True,
    )


def supp_inputs(book: dict) -> None:
    fusion = book["fusion"]
    oracle, delta, llp = (
        fusion["oracle_standardised"],
        fusion["oracle_standardised_delta"],
        fusion["llp"],
    )

    def cell(entry: dict) -> str:
        seeds = entry["seeds"]
        sd = (sum((x - entry["mean"]) ** 2 for x in seeds) / (len(seeds) - 1)) ** 0.5
        return f"{entry['mean']:.3f} ({sd:.3f})"

    rows = [f"Oracle & none (reference) & {cell(oracle['none'])} & \\\\"]
    for key, name in (("wc", "WorldCover"), ("aux", "GHSL + lights"), ("wc_aux", "both")):
        d = delta[key]
        rows.append(
            f"Oracle & {name} & {cell(oracle[key])} & {signed(d['mean'], d['ci_low'], d['ci_high'])}\\\\"
        )
    rows.append("\\midrule")
    rows.append(f"Map & none (reference) & {cell(llp['none'])} & \\\\")
    for key, name in (
        ("wc_early", "Map, early & WorldCover"),
        ("aux_early", "Map, early & GHSL + lights"),
        ("wc_aux_early", "Map, early & both"),
        ("aux_late", "Map, late & GHSL + lights"),
        ("wc_aux_late", "Map, late & both"),
    ):
        rows.append(f"{name} & {cell(llp[key])} & \\\\")
    table(
        "supp_inputs",
        "Global products offered to the model as input features, validation cities, "
        "within-municipality Spearman $\\rho$, mean and s.d. over three seeds, on the "
        "non-overlapping extraction of DOFA-B. GHSL built-up surface, building height, population "
        "and nighttime lights as four token columns; WorldCover as its eleven class fractions plus "
        "NDVI mean and dispersion. The oracle rows are standardized, with their own no-extras "
        "reference; the paired difference is per municipality, seed-averaged, with a city-clustered "
        f"bootstrap over {delta['aux']['municipalities']} municipalities. The map rows fuse the "
        "columns either into the projection (early) or straight into the scoring layer (late).",
        "llcc",
        "Head & Extra inputs & Within-$\\rho$, mean (s.d.) & Paired difference [95\\%]",
        rows,
        label="tab:inputs",
    )


def supp_finetune(book: dict) -> None:
    ft = book.get("finetune", {})
    by_lr = ft.get("by_encoder_lr", {})
    val = read("data/supervision_curve.csv")
    val = val[val.bags == 771] if val is not None else None
    test = read("data/test_column.csv")
    test = (
        test[(test.row == "curve") & (test.detail.astype(str) == "771")]
        if test is not None
        else None
    )
    rows = []
    if val is not None and test is not None:
        rows.append(
            f"Frozen (reference) & {val.spearman_within.mean():.3f} ({val.spearman_within.std():.3f}) & "
            f"{val.bag_mae.mean():.3f} & {test.spearman_within.mean():.3f} ({test.spearman_within.std():.3f}) & "
            f"{test.bag_mae.mean():.3f}\\\\"
        )
    for lr, label in (("1e-5", "$10^{-5}$"), ("1e-4", "$10^{-4}$")):
        f = by_lr.get(lr)
        if f:
            rows.append(
                f"Last two blocks trained, lr {label} & {f['val']['within']:.3f} ({f['val']['sd']:.3f}) & "
                f"{f['val']['bag_mae']:.3f} & {f['test']['within']:.3f} ({f['test']['sd']:.3f}) & {f['test']['bag_mae']:.3f}\\\\"
            )
    table(
        "supp_finetune",
        "Partial fine-tuning of DOFA-B on the municipal aggregates, non-overlapping extraction. "
        f"The last two of the twelve transformer blocks (from block {ft.get('split_at', 10)} on) and "
        "the final normalization are trained together with the head at the stated encoder learning "
        "rate, early-stopped on validation bag error like the frozen runs; the frozen row is the "
        "same head retrained on the frozen vectors. Within-municipality Spearman $\\rho$ of token "
        f"scores against tract grades, mean (s.d.) over {ft.get('seeds', 3)} seeds, and the bag "
        "error (mean absolute error of the predicted deprivation share) the training minimizes, on "
        "the validation and the held-out test cities.",
        "lcccc",
        "Extractor & Validation $\\rho$ & Val.\\ bag error & Test $\\rho$ & Test bag error",
        rows,
        label="tab:finetune",
    )


def classification(book: dict) -> None:
    view = read("data/classification_view.csv")
    rows = []
    for _tag, name in BACKBONES:
        for split in ("val", "test"):
            r = (
                view[(view.features == name) & (view.split == split)]
                if view is not None
                else pd.DataFrame()
            )
            if r.empty:
                rows.append(
                    f"{name} & {'validation' if split == 'val' else 'test'} & {DASH} & {DASH} & {DASH} & {DASH} & {DASH}\\\\"
                )
                continue
            r = r.iloc[0]
            rows.append(
                f"{name} & {'validation' if split == 'val' else 'test'} & {thousands(r.tracts)} & {r.kappa_quadratic:.3f} & {r.accuracy:.3f} & {r.auroc_thresholds_pooled:.3f} & {r.auroc_thresholds_within:.3f}\\\\"
            )
    table(
        "classification",
        "The map read as a five-grade classifier. Tract-mean scores of the seed ensemble; the grade "
        "is assigned by the isotonic score-to-grade map fitted on the validation tracts. $\\kappa$ "
        "is quadratic-weighted Cohen's kappa and accuracy is over the five grades, both pooled over "
        "the split's tracts; AUROC is the mean over the four cumulative thresholds (grade at least "
        "$k$), pooled over the split and averaged over the 22 municipalities with at least twenty "
        "tracts.",
        "llrcccc",
        "Features & Split & Tracts & Quadratic $\\kappa$ & Accuracy & AUROC, pooled & AUROC, within",
        rows,
        label="tab:classification",
    )


def products(book: dict) -> None:
    labels = {
        "built_surface": "GHSL built-up surface",
        "built_height": "GHSL building height",
        "population": "GHSL population",
        "nightlights": "Nighttime lights",
    }
    frames = {
        (tag, split): read(
            suffixed(f"data/global_products{'_test' if split == 'test' else ''}.csv", tag)
        )
        for tag, _ in BACKBONES
        for split in ("val", "test")
    }
    aurocs = []
    for tag, name in BACKBONES:
        v, t = frames[(tag, "val")], frames[(tag, "test")]
        aurocs.append(
            f"{fmt(v.ours_auc_high.iloc[0] if v is not None else None)} on validation and {fmt(t.ours_auc_high.iloc[0] if t is not None else None)} on test with {name}"
        )
    rows = []
    for product, label in labels.items():
        for split in ("val", "test"):
            first = frames[(BACKBONES[0][0], split)]
            cells = [label if split == "val" else "", split]
            if first is None:
                cells.append(DASH)
            else:
                p = first.set_index("product").loc[product]
                cells.append(
                    ci(p.proxy_within, p.proxy_ci_low, p.proxy_ci_high)
                    .replace("[-", "[$-$")
                    .replace(", -", ", $-$")
                )
            for tag, _ in BACKBONES:
                f = frames[(tag, split)]
                if f is None:
                    cells += [DASH, DASH]
                    continue
                p = f.set_index("product").loc[product]
                cells += [
                    ci(p.ours_within, p.ours_ci_low, p.ours_ci_high),
                    signed(p.difference, p.ci_low, p.ci_high),
                ]
            cells.append(
                fmt(first.set_index("product").loc[product].proxy_auc_high)
                if first is not None
                else DASH
            )
            rows.append(" & ".join(cells) + "\\\\")
    header = f" & & & \\multicolumn{{2}}{{c}}{{{BACKBONES[0][1]}}} & \\multicolumn{{2}}{{c}}{{{BACKBONES[1][1]}}} & \\\\\n\\cmidrule(lr){{4-5}}\\cmidrule(lr){{6-7}}\nProduct & Split & Product $\\rho$ [95\\%] & Map $\\rho$ [95\\%] & $\\Delta$ [95\\%] & Map $\\rho$ [95\\%] & $\\Delta$ [95\\%] & AUROC product"
    table(
        "products",
        "Free global products under the map's own protocol, for both feature extractors. "
        "Within-$\\rho$ is the mean over municipalities of the within-municipality Spearman "
        "correlation against the held-out tract grade on the identical universe (22 municipalities "
        "per split), each with its 95\\% percentile bootstrap over cities; $\\Delta$ is the paired "
        "difference, map minus product, on the same city draws. AUROC is pooled detection of high "
        f"and very-high grade tracts across the split (map: {aurocs[0]}, {aurocs[1]}). Orientation "
        "was fixed before measurement: deprivation is the negative of every product. The "
        "nighttime-light row rests on interior-point sampling for 63\\% of tracts, which are "
        "smaller than one of its 30 arcsec cells.",
        "llcccccc",
        header,
        rows,
        label="tab:products",
        resize=True,
    )


def conformal(book: dict) -> None:
    names = dict(pd.read_csv("data/cities_national.csv")[["key", "name"]].to_numpy())
    rows = []
    for tag, name in BACKBONES:
        f = read(suffixed("data/uncertainty_conformal.csv", tag))
        for rule, label in (("marginal", "marginal"), ("clustered", "clustered by city")):
            if f is None:
                rows.append(f"{name} & {label} & {DASH} & {DASH} & {DASH} & {DASH}\\\\")
                continue
            r = f.set_index("rule").loc[rule]
            rows.append(
                f"{name} & {label} & {r.half_width_grades:.2f} & {r.coverage:.3f} & {names.get(r.worst_city, r.worst_city)} ({r.worst_city_coverage:.3f}) & {int(r.cities_below_nominal)} of {int(r.cities)}\\\\"
            )
    table(
        "conformal",
        "Conformal grade intervals at 90\\% nominal coverage, calibrated on the validation cities "
        "and evaluated on the test cities, for both feature extractors. The marginal rule assumes "
        "all tracts exchangeable; the clustered rule takes each calibration city's quantile and "
        "then the 90th percentile across cities.",
        "llcccc",
        "Features & Rule & Half-width (grades) & Coverage & Worst city (coverage) & Cities below nominal",
        rows,
        label="tab:conformal",
    )


def audit(book: dict) -> None:
    names = dict(pd.read_csv("data/cities_national.csv")[["key", "name"]].to_numpy())
    first = read(suffixed("data/city_audit_test.csv", BACKBONES[0][0]))
    second = read(suffixed("data/city_audit_test.csv", BACKBONES[1][0]))
    rows = []
    if first is not None:
        other = second.set_index("city") if second is not None else None
        for _, r in first.sort_values("rho_within").iterrows():
            cells = [
                names.get(r.city, r.city),
                str(int(r.municipalities)),
                str(int(r.agebs)),
                f"${r.rho_within:.3f}$",
                f"{r.median_spread:.3f}",
            ]
            if other is not None and r.city in other.index:
                o = other.loc[r.city]
                cells += [f"${o.rho_within:.3f}$", f"{o.median_spread:.3f}"]
            else:
                cells += [DASH, DASH]
            rows.append(" & ".join(cells) + "\\\\")
    header = f" & & & \\multicolumn{{2}}{{c}}{{{BACKBONES[0][1]}}} & \\multicolumn{{2}}{{c}}{{{BACKBONES[1][1]}}}\\\\\n\\cmidrule(lr){{4-5}}\\cmidrule(lr){{6-7}}\nCity & Municipalities & Tracts & Within-$\\rho$ & Seed spread & Within-$\\rho$ & Seed spread"
    table(
        "audit",
        "The fourteen test cities ranked by the within-municipality correlation their map achieves "
        f"with {BACKBONES[0][1]}, worst first, with the {BACKBONES[1][1]} value beside it. Tract-mean "
        "scores. Spread is the median across tracts of the standard deviation over three seeds, "
        "which does not separate the failures from the successes.",
        "lrrrrrr",
        header,
        rows,
        label="tab:audit",
    )


def maup(book: dict) -> None:
    frames = {tag: read(suffixed("data/maup.csv", tag)) for tag, _ in BACKBONES}
    first = frames[BACKBONES[0][0]]
    rows = []
    if first is not None:
        for i, r in first.iterrows():
            span = (
                f"{int(r.tokens_low)}--{int(r.tokens_high)}"
                if r.tokens_high < 10000
                else f"$\\geq${int(r.tokens_low)}"
            )
            cells = [
                span,
                str(int(r.agebs)),
                thousands(r.median_population),
                str(int(r.municipalities)),
            ]
            for tag, _ in BACKBONES:
                f = frames[tag]
                cells.append(
                    fmt(f.iloc[i].spearman_within) if f is not None and i < len(f) else DASH
                )
            rows.append(" & ".join(cells) + "\\\\")
    table(
        "maup",
        "Agreement by tract size on the validation cities. Within-municipality Spearman $\\rho$ of "
        "tract-mean scores over municipalities with at least ten tracts in the bin, for both feature "
        "extractors.",
        "rrrrcc",
        f"Tokens per tract & Tracts & Median population & Municipalities & {BACKBONES[0][1]} & {BACKBONES[1][1]}",
        rows,
        label="tab:maup",
    )


HEAD_NAMES = {
    "cumulative": "cumulative thresholds (reference)",
    "coral": "CORAL",
    "softmax": "softmax, cross-entropy",
}


def heads(book: dict) -> None:
    frame = read("data/head_ablation.csv")
    rows = []
    diffs = []
    for _tag, name in BACKBONES:
        for head, label in HEAD_NAMES.items():
            sub = (
                frame[(frame["features"] == name) & (frame["head"] == head)]
                if frame is not None
                else None
            )
            cells = []
            for split in ("val", "test", "cv"):
                r = sub[sub["split"] == split] if sub is not None else None
                if r is None or r.empty:
                    cells.append(DASH)
                    continue
                r = r.iloc[0]
                cells.append(ci(r.within_token, r.within_token_low, r.within_token_high))
            r = sub[sub["split"] == "cv"] if sub is not None else None
            cells.append(
                ci(r.iloc[0].within_ageb, r.iloc[0].within_ageb_low, r.iloc[0].within_ageb_high)
                if r is not None and not r.empty
                else DASH
            )
            r = sub[sub["split"] == "test"] if sub is not None else None
            cells.append(
                f"{r.iloc[0].kappa_quadratic:.3f}" if r is not None and not r.empty else DASH
            )
            cells.append(f"{r.iloc[0].bag_mae:.3f}" if r is not None and not r.empty else DASH)
            rows.append(f"{name} & {label} & " + " & ".join(cells) + "\\\\")
            r = sub[sub["split"] == "cv"] if sub is not None else None
            if head != "cumulative" and r is not None and not r.empty and "diff_token" in r:
                r = r.iloc[0]
                if r.notna().get("diff_token", False):
                    diffs.append(
                        f"{name} & {label} minus reference & & & "
                        f"{signed(r.diff_token, r.diff_token_low, r.diff_token_high)} & "
                        f"{signed(r.diff_ageb, r.diff_ageb_low, r.diff_ageb_high)} & & \\\\"
                    )
    if diffs:
        rows.append("\\midrule")
        rows.extend(diffs)
    table(
        "heads",
        "Parameterisation of the instance head under one protocol, both feature extractors. "
        "The reference head predicts four cumulative shares with independent thresholds; CORAL "
        "shares one weight vector across the thresholds; the softmax head predicts five class "
        "probabilities and is trained with cross-entropy on the class shares of the bag. "
        "Within-municipality Spearman $\\rho$ of the seed-mean token score against tract "
        "grades, mean over municipalities, per token on the validation cities (selection) and "
        "the held-out test cities, and per token and per AGEB under grouped five-fold "
        "cross-validation over the 138 cities; brackets are 95\\% percentile bootstraps "
        "resampling cities, and the differences are paired against the reference head on the "
        "same city draws. $\\kappa$ is the quadratic-weighted kappa of the isotonic grade on "
        "the test tracts; bag error is the mean absolute error of the four cumulative shares "
        "on the test municipalities, the quantity the training minimizes.",
        "llcccccc",
        "Features & Head & Validation & Test & CV, token & CV, AGEB & $\\kappa$, test & Bag error, test",
        rows,
        label="tab:heads",
        resize=True,
    )


def transfer(book: dict) -> None:
    names = {
        "zero-shot": "Mexican, unadapted",
        "mexico-init": "Mexican, fine-tuned",
        "oracle": "oracle",
    }
    order = [
        "zero-shot",
        "aggregates@50",
        "aggregates@100",
        "aggregates@200",
        "aggregates@400",
        "aggregates",
        "mexico-init",
        "oracle",
    ]
    rows = []
    info = {}
    for country in ("colombia", "brazil"):
        for tag, name in BACKBONES:
            frame = read(suffixed("data/transfer_training.csv", tag))
            if frame is None:
                rows.append(f"{country.capitalize()} & {name} & {DASH} & {DASH} & {DASH}\\\\")
                continue
            t = frame[frame.country == country]
            bags = int(t.bags.iloc[0])
            info.setdefault(country, {})[tag] = (
                bags,
                int(t.tokens_scored.iloc[0]),
                int(t.municipalities_scored.iloc[0]),
            )
            for m in order:
                r = t[t.method == m]
                if r.empty:
                    continue
                label = names.get(
                    m, f"local aggregates, {m.split('@')[1] if '@' in m else bags} bags"
                )
                mean = r.within.mean()
                if country == "brazil":
                    cell = (
                        f"{mean:.3f} [{r.within_ci_low.mean():.3f}, {r.within_ci_high.mean():.3f}]"
                    )
                else:
                    cell = f"{mean:.3f}" + (f" ({r.within.std():.3f})" if len(r) > 1 else "")
                rows.append(
                    f"{country.capitalize()} & {name} & {label} & {cell} & {r.auroc_top_quartile.mean():.3f}\\\\"
                )
        if country == "colombia":
            rows.append("\\midrule")
    col = info.get("colombia", {}).get(BACKBONES[0][0], (0, 0, 0))
    bra = info.get("brazil", {}).get(BACKBONES[0][0], (0, 0, 0))
    table(
        "transfer",
        "Transfer under each country's own municipal aggregates (Fig.~\\ref{fig:validation}d), for "
        "both feature extractors on the same bags. Within-municipality Spearman against the fine "
        "truth, grouped five-fold by municipality, mean over three seeds; Bogot\\'a's oracle folds "
        f"over 3.2 km spatial cells. Colombia: {col[0]} bags, the Bogot\\'a block strata as truth "
        f"over {thousands(col[1])} built tokens, so the within-municipality value is the correlation "
        "inside that one municipality and the parenthesis is the s.d. over seeds (the unadapted "
        f"model has one). Brazil: {bra[0]} bags, tract median income of the household head as truth "
        f"over {thousands(bra[1])} tokens in {bra[2]} municipalities, with the 95\\% "
        "municipality-bootstrap interval of the mean. AUROC is for the most deprived quartile of "
        "the truth, pooled.",
        "lllcc",
        "Country & Features & Method & Within-$\\rho$ & AUROC",
        rows,
        label="tab:transfer",
        resize=True,
    )


def main() -> None:
    book = canon()
    for build in (
        curve,
        backbone_cv,
        features,
        classification,
        products,
        conformal,
        audit,
        maup,
        transfer,
        heads,
        supp_backbone_cv,
        supp_inputs,
        supp_finetune,
        supp_curve,
    ):
        build(book)
    print(f"tables written to {OUT}", flush=True)


if __name__ == "__main__":
    main()
